//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.01 at 04:05:58 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.sakthivel.com/spring/soap/api/test", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sakthivel.spring.soap.api.test;
